#pragma once

enum
{
    EVENT_UPDATE_LIST = 0x2000,
    EVENT_EMULATION_LOADING,
    EVENT_EMULATION_RUNNING,
    EVENT_EMULATION_STOPPED,
    EVENT_EMULATION_FIRST_FRAME,
    EVENT_DISK_CACHE_STATUS,
    EVENT_FIRMWARE_INSTALL_DONE,
    EVENT_FIRMWARE_INSTALL_ACTIVE,
    EVENT_EXECUTE_PROGRAM,
    EVENT_EXIT_PROGRAM,
    EVENT_RELOAD_PROGRAM,
    EVENT_PROFILE_SELECT,
};
